apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: shop-redirect-slash
spec:
  redirectRegex:
    regex: ^(https?://[^/]+/shop)$
    replacement: ${1}/
    permanent: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: default-shop-redirect-slash@kubernetescrd
  name: shop
spec:
  ingressClassName: kommander-traefik
  rules:
  - http:
      paths:
      - backend:
          service:
            name: frontend
            port:
              number: 80
        path: /shop
        pathType: ImplementationSpecific